### PR TITLE
Updates from Debian packaging

### PR DESCRIPTION
**Pull request by olekw**
These six commits are based on changes to Ember in Debian. Four are based on Debian policy-mandated fixes and two are just errors noticed while preparing the Debian package. All of these changes should be useful in Ember outside of Debian, ergo this pull request.

### CODE REVIEW

**Comment by erikogenvik** [comment]
These all look good. The only one I'm a bit wary about is the addition of "objects-subdir". I remember testing adding it to Cyphesis and Ember some years ago (when the build system started complaining about it) but ran into trouble. I don't exactly remember the cause; either there were something which didn't fully work, or it was an issue with backwards-compatibility. I'll do some more tests.

However, will there also be patches for Cyphesis? The problem is that these patches relies on the patches for wfmath, but those patches will currently break Cyphesis.

**Comment by erikogenvik** [comment]
Ok, just verified that the subdir-objects directive doesn't build on Ubuntu 16.04 at least due to how src/main/Makefile.am references source files using absolute path.
Which is something we have in order to make it easier to build the WebEmber plugin.
But does it compile on Debian?

**Comment by olekw** [comment]
Erik: Yes, let's definitely get to the bottom of this! The strange thing is that Ember compiles perfectly on Debian Sid. Could you please send me your build log file? Also, I'm not aware of any problems in Cyphesis. Cyphesis has been building perfectly on 19 different architectures in Debian for about 21 months using the patched WFMath package. Again, if you see a build failure please send me your log file and I'll do my best to track down the problem!

**Comment by olekw** [comment]
Erik: I was concerned that there might be a problem with my build environment so I built the Ember package in my Ubuntu PPA. It built without any problems. See here for build log etc.: https://launchpad.net/~olekw/+archive/ubuntu/worldforge/+build/10540492

Also, just added another commit to make the icon location compliant with the Icon Theme Specification. It apparently wasn't showing up on people's menus. I was able to confirm the missing icon behavior in Xfce but it was also reported in KDE.

**Comment by olekw** [comment]
And another addition, I was finally able to track down what was causing some random build failures such as this one: https://launchpadlibrarian.net/276660069/buildlog_ubuntu-yakkety-amd64.ember_0.7.2+dfsg-1ubuntu1_BUILDING.txt.gz

**Comment by erikogenvik** [comment]
Awesome! I've been seeing those random build failures for a while, but they were never enough frequent for me to figure out what was wrong.

I've also found the cause of the build failures. Caused by a bug in Automake, which doesn't expand paths when subdir-objects is used. See https://lists.gnu.org/archive/html/automake/2015-08/msg00004.html and http://debbugs.gnu.org/13928.
I have a fix.

**Pull request merged**
